### ISSUE TITLE
Is Clash Of Lights Allowed To Make UCS close source?

### ISSUE THREAD

**Issue by aididhaiqal** [jeanbmar/wow_outlaw_rogue_rotation#1]
Is Clash Of Lights Allowed To Make UCS close source?He basically using UCS as his income...Recently he charged FHX 2000$ for UCS and he also sued other server like COM for reason using "Leaked UCS" when basically the server owner is using CoCSharp...Also,He claiming UCS is his...Because he work on it..(I give UCS 8.702 support,So shouldn't it be mine if that the case? xD)

**Comment by jeanbmar** [comment]
GPL license of UCS implies:
- People can take UCS source and build whatever they want on top of it
- People don't have to distribute their work based on UCS
- If people choose to distribute (and possibly sell) their work based on UCS, they are free to do it privately
- Distributed work based on UCS (free or not) must follow the GPL license
- Anyone receiving a legit copy of a software built on top of UCS can require the source code of the entire application (GPL license applies)

Wrong repo btw.

**Comment by goldbi** [comment]
Are you happy now aidid?
With this, now you can tell to your friend Patrik to close directly the server before his hoster do it :)
And don't tell lies please, Clash of Lights decided nothing, all changed was authorized by me (switch to closed source, Dmca video/links/servers that was using a **# NON LEGIT COPY** of ucs) . Since i'm the only in charge to do it for the moment :)

**Comment by OMGItssCrayCray** [comment]
Oh shut the fuck up Eiffel.

**Comment by DarkSoulGaming** [comment]
@goldbi why does patrik website hosting has to do with his servers on which he hosted UCS? He never hosted UCS on his web server which makes your dmca a false claim even if you could take-down his hosting, remember he can still buy hosting from else-where :D and the UCS we received was under Apache-2 license and then it was later changed to whatever shitty license you're using just to take down his or my server.

**Comment by expl0itr** [comment]
@goldbi Hey Antonio, how are you doing? Hope that your business squeezes profit from the "high-quality work".

**Comment by goldbi** [comment]
@OMGItssCrayCray 
You should be grateful for what you had. 
I'm not referring about the skill you learned thanks to this adventure, i'm referring about you had a friend who you betrayed on his back apparently for no reason.
You now,  want to do the guy with morals, but, i need just to show this to let understand what kind of person you are :)

http://imgur.com/a/oMLg3 

Lies on lies. Lies on Me, lies to Fhx and lies on ucs. Please make a favor to everyone and just grow up.
If the paypal story wasn't enough for you, look like i have to go talk with your parents about Your irresponsible behavior.

**Comment by goldbi** [comment]
@DarkSoulGaming 
I'm just confused to have you here, 
We talked some time ago and i just told to you that your server wasn't involved in any action at the moment.
I'm kinda disappointed of you act to be here and defend someone that yourself know that he is guilty.
Beside to this, I did not know you were a lawyer since you look like so prepared about the 17 USC 512(c)(3)(A) :)

But to your question, i will not give a reply, i will only says "As he can buy new hosts, we can send new letters" and to every new one, we will insert more further evidence, in this way the host will shut down the service every time more faster! 

To your edit: I'm not jealous but we are disgusted, as your self said " Clash of Magic etc earn more in a day than you do in a month!" Well I'm happy for that, but you all should be grateful for what we made. We are not the greedy here, the greedy are the one that make xxxx of dollars monthly thanks an OUR work where they just want give to us back a single-time 25$ donation.  Please.

**Comment by OMGItssCrayCray** [comment]
Lol, you call me irresponsible or immature come on man think of a better excuse than that. I am perfectly fine as is. I mean at least I don't go into PayPal and lie about everything just to get $50 back.

**Comment by OMGItssCrayCray** [comment]
Lol, you call me irresponsible or immature? C'mon man think of a better response than that. I am perfect fine as is and lets just be thankful I'm not like you who lies to PayPal to slip $50 back.

**Comment by BerkanYildiz** [comment]
![image](https://cloud.githubusercontent.com/assets/15068742/22120364/bace5cce-de7f-11e6-992c-043cda0edd31.png)

**Comment by OMGItssCrayCray** [comment]
_*Patiently waits for @jeanbmar to reply*_

**Comment by PatrikCoC** [comment]
I already told you, @goldbi the reason. I will not expect you to understand my situation, neither I want to have this as an excuse. My server is using 8.551 which is not based on the source that **a staff member (permission)** gave us.

**Comment by ClashofJeann** [comment]
-so @OMGItssCrayCray free ucs? Did we say that you need to pay for it. Donation based ? who? kids as you/me? Why berkan left UCS? a bit to get money because we don't get anything for the time we invest. ---@PatrikCoC paid you 500$ (even if it's not 500$) for source why didn't he buy a licence for UCS and avoid DMCA. 
-We had trust in you craycray, aidid and you betrayed us so immature/irresponsible is a little word.
-@expl0itr "high-quality work" can you do better? (Ik you'll say yes because your ego is too big)
-**_IT'S YOUR FAULT_**, you betrayed us, you leaked the source, you used it, we don't want to loose time with these stupid games. 
 ASSUME don't cry in @jeanbmar repo.

The only 1 who understands rules is Fhx, he trusts us because we don't betray as you.

Respectfully,
Metrogaming

**Comment by DarkSoulGaming** [comment]
@goldbi Well yes I know you have told me that my server isnt involved but you also need to understand the current situation Patrik is going through... DMCA is not a thing that you just give out to everyone for fun or whatever.

I'm not a lawyer I'm just trying to prove something and yup I did went through some of 7 USC 512(c)(3)(A) documentation to defend myself against supercell not ultrapowa cuz I knew Jean would never do such thing like that but now that you've come, you started to DMCA everyone which I didn't expect you to do.
Disappointed in me? you just said that you will keep sending letters to every host he buys even tho he wouldnt be using UCS anymore.... that explains it all....

I have always been thankful to ULTRAPOWA for creating UCS which made our life easier than before... We even gave credits to ultrapowa on our site (removed it when u said that u will dmca us) and about donation i did donate twice but my donor status was revoked for giving out sc editor.. once i gave it to one of my friend and the second time i shared it with aidid (he was donor too) so idk why jean revoked my status that that... i did try to explain everything to him but maybe he didnt understand me clearly... but yeah first time it was my fault and then i never even asked for refund... even if we donate $25 we would still not get the ucs that was leaked to us cuz what i heard was that you sold one license for like $2k to fhx.. do u really think that we will pay $2k for that?

(sorry for my bad english xD)

**Comment by expl0itr** [comment]
@ClashofJeann 
![b34](https://cloud.githubusercontent.com/assets/8836484/22123926/068d2114-de8e-11e6-924e-137faba117cb.jpg)

**Comment by OMGItssCrayCray** [comment]
LOL

**Comment by OMGItssCrayCray** [comment]
Ouch it hurt @ClashofJeann but hey I did a favour for Patrik by not ripping him off.

**Comment by BerkanYildiz** [comment]
![image](https://cloud.githubusercontent.com/assets/15068742/22124082/9f0d752e-de8e-11e6-9d8b-91c2a503f15c.png)

**Comment by ClashofJeann** [comment]
@DarkSoulGaming didn't revoke your donor status ^^

**Comment by DarkSoulGaming** [comment]
@ClashofJeann well ofc the license was sold to fhx for $2k... how can u say that it's free? it wasnt even free to donators..
even if patrik paid him $500.. wasn't cray the head developer? and apache 2 license clearly states that any authorized member is allowed to share his/her work with anyone.
It was never his fault, he never betrayed anyone.... why didnt anything like this happen before? it's because ucs was free before ultrapowa left and then the new community admins and whoever they were decided to sell ucs for fucking $2k... it isnt a small amount... talking about time? we never invited you guys here... it was just aidid asking something from jean and u decided to hop-in outa no where.

**Comment by DarkSoulGaming** [comment]
@ClashofJeann didnt revoke my donor status what?

**Comment by BerkanYildiz** [comment]
@DarkSoulGaming @OMGItssCrayCray @aididhaiqal @expl0itr @PatrikCoC 
Can you guys just forget Ultrapowa.com, nobody cares about them. It's a dead meme !

![image](https://cloud.githubusercontent.com/assets/15068742/22124186/f8892d50-de8e-11e6-97c1-7939722c6ef4.png)

**Comment by BerkanYildiz** [comment]
@goldbi @ClashofJeann @ClashOfLights
![image](https://cloud.githubusercontent.com/assets/15068742/22124203/0a484eb8-de8f-11e6-8918-06e1070f0e86.png)

**Comment by DarkSoulGaming** [comment]
@BerkanYildiz lmao bruh give us latest GCS then xD

**Comment by OMGItssCrayCray** [comment]
@BerkanYildiz It's hard when they are constantly abusing services like DMCA, Paypal and so on.

**Comment by ClashofJeann** [comment]
@BerkanYildiz just shut up and get out of this topic you're useless with your memes. Just do as you said "forget" the "dead" ultrapowa

**Comment by BerkanYildiz** [comment]
@OMGItssCrayCray Aw, You're riiight !
@DarkSoulGaming , Nice try

**Comment by BerkanYildiz** [comment]
@ClashofJeann Don't insult people, you're the one who need to be insulted 🗡

**Comment by BerkanYildiz** [comment]
@ClashofJeann 
![image](https://cloud.githubusercontent.com/assets/15068742/22124309/937bfe78-de8f-11e6-83c3-f5c3d50ebc27.png)

**Comment by ClashofJeann** [comment]
From you it's almost a compliment asshole <3

**Comment by expl0itr** [comment]
@ClashofJeann You take yourself too seriously. "Jeann".

**Comment by BerkanYildiz** [comment]
![image](https://cloud.githubusercontent.com/assets/15068742/22126980/56496fa8-de9a-11e6-88e1-c401e8458808.png)

**Comment by BerkanYildiz** [comment]
![image](https://cloud.githubusercontent.com/assets/15068742/22127035/800b79d0-de9a-11e6-8d95-1684e926cf8e.png)

**Comment by jeanbmar** [comment]
Recreation time is over, thanks everybody

**Comment by OMGItssCrayCray** [comment]
Recreation time isn't over till the issue is resolved. In this case its just getting started.

**Comment by josemanosalvas** [comment]
The dark side of github. I was here.
